jitaccess.ops NS delegation
PHACDataHub/dns pull request #20
Opened 2023-08-14 20:09 UTC by ericmalen

2023-08-14 23:21 UTC, KingBain commented on dns-records/jitaccess.ops.phac.alpha.canada.ca.yaml
> +    gitHubRepo: "JIT-IaC"
could you change that to a URL, even if it's private. I will ask that @sleepycat confirm that's fine.

2023-08-14 23:22 UTC, KingBain commented on dns-records/jitaccess.ops.phac.alpha.canada.ca.yaml
> +    external: phac-alpha-canada-ca
I think this needs to be 
```suggestion
external: ops-phac-alpha-canada-ca-zone 
```

2023-08-14 23:23 UTC, KingBain requested changes
Let me know what you think of the changes

2023-08-15 00:37 UTC, ericmalen commented on dns-records/jitaccess.ops.phac.alpha.canada.ca.yaml
> +    external: phac-alpha-canada-ca
Done

2023-08-15 17:42 UTC, merged